# Generated by Django 4.2.6 on 2023-10-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirrurl',
            name='shortcode',
            field=models.CharField(default='shortUrlcode', max_length=15),
            preserve_default=False,
        ),
    ]
